### PR TITLE
add stop_word_removal on sastrawi.rb

### PR DESCRIPTION
**Pull request by slmnabd**

### CODE REVIEW

**Comment by meisyal** [comment]
Hi @slmnabd,

Thank you for the PR. I have some questions.
1. Why do we import `stop_word_remover_factory`?
2. Any use case for that? Could you give an example?

**Comment by slmnabd** [comment]
because I can't use that.
when I try `Sastrawi::StopWordRemover::StopWordRemoverFactory.new`
I found an error message like this `uninitialized constant
Sastrawi::StopWordRemover'

I need to use stop_word_remover to text data preprocessing. because this
the step is needed in the VSM (Vector Space Model) method

**Comment by meisyal** [comment]
I see. So, you want to use stop word remover feature.

The main feature of this library actually is stemming words. Removing stop words isn't included. OK, I will accept your PR after you exclude or remove `Gemfile.lock` from this PR. `Gemfile.lock` file should be ignored as defined on https://github.com/meisyal/sastrawi-ruby/blob/dev/.gitignore#L45. Could you exclude that @slmnabd?

**Comment by meisyal** [comment]
Thank you @slmnabd for the contribution.

I have merged your PR. Your changes will be included on the next release. It's scheduled tomorrow.

**Pull request merged**
